### ISSUE TITLE
Bug in the client [BUG #001]

### ISSUE THREAD

**Issue by nikhilr612** [hulsemohit/MediKinesis#4]
> #### This is a crucial bug that needs to be fixed immediately.
This BUG arises due to the PIN on the user side not being set. 

Here is an extract of  the output,
```
Log ........
view null
Log .......
```

As you can see the client API doesn't actually send the PIN simply because the gloabl variables haven't been updated. Please fix this immediately

**Comment by hulsemohit** [comment]
@nikhil10marvel  I have just fixed this problem.
