### ISSUE TITLE
Bug In App [BUG #002]

### ISSUE THREAD

**Issue by nikhilr612** [hulsemohit/MediKinesis#5]
>**This is a critical bug, that needs to be fixed immediately**

The app is unable to handle `chkusr` statements from the server. It can only handle true results, but not false. @hulsemohit please __*fix*__ this _immediately_.

The issue is just that when the user tries to report with a name that already exists, the app just pops up with Unfortunately, Medikinesis has stopped

**Comment by hulsemohit** [comment]
Fixed
