### ISSUE TITLE
Important library missing

### ISSUE THREAD

**Issue by nikhilr612** [hulsemohit/MediKinesis#8]
@hulsemohit, The client side `mdknet-client-debug.jar` ( A very important networking library is missing) in the app source which may lead to errors while importing it to android studio or IntelliJ.

Currently the only workaround on this is to manually get the lib file from the repository[1] and place it in the `libs`[2] folder.

Hope this inconvenience is resolved.

[1] - [mdkcli/dist/mdknet-client-debug.jar](https://github.com/hulsemohit/MediKinesis/blob/master/mdkcli/dist/mdknet-client-debug.jar) 
[2] - `{appsource}/libs` folder

**Comment by hulsemohit** [comment]
No,
I removed the file from appsource on purpose as the file size was too large
and the same file can be obtained in another folder....
Check my comment next to the appsource....

**Comment by nikhilr612** [comment]
Alright, we need the app source to be in such a condition that it can easily be imported  into any of the modern utilities such as intelliJ or android studio

Currently, it's only a module which has to be imported in an indirect way
